[[env]]
name = "API_JS_PATH"
eval = "$PRJ_ROOT/frontend/api.js"

[[env]]
name = "HOOGLE_PORT"
value = "9500"

[[env]]
name = "API_SPEC_PATH"
eval = "${PRJ_ROOT}/api-spec.json"

[[commands]]
package = "sqitchPg"
name = "sqitch"
category = "DB"

[[commands]]
package = "openapi-generator-cli"
category = "openapi"

[[commands]]
name = "gen-ts"
help = "generate typescript client"
command = '''
        rm -rf $PRJ_ROOT/frontend/genstub
        openapi-generator-cli generate -i "$API_SPEC_PATH" -g typescript-axios -o "$PRJ_ROOT/frontend/genstub"
        ''' 
category = "openapi"

[[commands]]
name = "doc"
command = '''
echo http://127.0.0.1:$HOOGLE_PORT
hoogle serve -p $HOOGLE_PORT --local
          '''
help = "run hoogle server locally for documentation"
category = "Haskell tools"
